var express = require("express");
var app = express();
var path = require("path");
var routes = require("./routes/routes");
var bodyParser = require('body-parser');
app.use(express.static(path.join(__dirname, '/public/')));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
routes(app);
app.listen(3000);
console.log('Node server running on port 3000');